import React, { createContext, useState, useReducer, useEffect } from 'react';

export const PosContext = createContext();

const ticketReducer = (state, action) => {
  switch (action.type) {
    case 'ADD_ITEM':
      // The payload may have a cartItemId generated by PosGrid
      const cartItemId = action.payload.cartItemId || action.payload.id;
      const existingItem = state.find(item => (item.cartItemId || item.id) === cartItemId);
      if (existingItem) {
        return state.map(item => 
          (item.cartItemId || item.id) === cartItemId ? { ...item, quantity: item.quantity + 1 } : item
        );
      }
      return [...state, { ...action.payload, cartItemId, quantity: 1 }];
    case 'REMOVE_ITEM':
      const targetId = action.payload.cartItemId || action.payload.id;
      return state.filter(item => (item.cartItemId || item.id) !== targetId);
    case 'UPDATE_QUANTITY':
        const targetUpdateId = action.payload.cartItemId || action.payload.id;
        return state.map(item => 
            (item.cartItemId || item.id) === targetUpdateId ? { ...item, quantity: action.payload.quantity } : item
        );
    case 'CLEAR_TICKET':
      return [];
    default:
      return state;
  }
};

export const PosProvider = ({ children }) => {
  const [activeTicket, dispatchTicket] = useReducer(ticketReducer, []);
  const [selectedCategory, setSelectedCategory] = useState('All');
  const savedUser = localStorage.getItem('spos_user');
  const [user, setUser] = useState(savedUser ? JSON.parse(savedUser) : { id: 1, name: 'Guest', role: 'Cashier' });
  const [menuItems, setMenuItems] = useState([]);
  
  const fetchMenu = async () => {
      try {
          const res = await fetch('http://localhost:5000/api/products?branch_id=1');
          const data = await res.json();
          // The products API returns an array directly, not {success: true, items: ...}
          if (Array.isArray(data)) {
              setMenuItems(data);
          }
      } catch (e) {
          console.error("Failed to fetch menu", e);
      }
  };

  useEffect(() => {
      if (user) {
          localStorage.setItem('spos_user', JSON.stringify(user));
          fetchMenu();
      } else {
          localStorage.removeItem('spos_user');
      }
  }, [user]);

  return (
    <PosContext.Provider value={{ 
        activeTicket, 
        dispatchTicket, 
        selectedCategory, 
        setSelectedCategory,
        user,
        setUser,
        menuItems
    }}>
      {children}
    </PosContext.Provider>
  );
};
